-- Database: GLOBALPLA Metadata version: 2 Exported: Jun 27, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5617_QUOTE_LINE_EXTRA_USER_FIELDS" USING 'GCG_5617_QUOTE_LINE_EXTRA_USER_FIELDS.mkd' PAGESIZE=4096 (
 "QL_UF6" CHAR(100),
 "QL_UF7" CHAR(100),
 "QL_UF8" CHAR(100),
 "QL_UF9" CHAR(100),
 "QL_UF10" CHAR(100),
 "QUOTE_NO" CHAR(7),
 "QUOTE_LINE" CHAR(3) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
