-- Database: GLOBALPLA Metadata version: 2 Exported: Jun 28, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5617_ORDER_LINE_EXTRA_USER_FIELDS" USING 'GCG_5617_ORDER_LINE_EXTRA_USER_FIELDS.mkd' PAGESIZE=4096 (
 "OL_UF6" CHAR(100),
 "OL_UF7" CHAR(100),
 "OL_UF8" CHAR(100),
 "OL_UF9" CHAR(100),
 "OL_UF10" CHAR(100),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
