-- Database: GLOBALPLA Metadata version: 2 Exported: Jun 28, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5617_ORDER_EXTRA_UF_CAPTION" USING 'GCG_5617_ORDER_EXTRA_UF_CAPTION.mkd' PAGESIZE=4096 (
 "OH_UF6" CHAR(50),
 "OH_UF6_REQUIRED" BIT NOT NULL,
 "OH_UF7" CHAR(50),
 "OH_UF7_REQUIRED" BIT NOT NULL,
 "OH_UF8" CHAR(50),
 "OH_UF8_REQUIRED" BIT NOT NULL,
 "OH_UF9" CHAR(50),
 "OH_UF9_REQUIRED" BIT NOT NULL,
 "OH_UF10" CHAR(50),
 "OH_UF10_REQUIRED" BIT NOT NULL,
 "OL_UF6" CHAR(50),
 "OL_UF6_REQUIRED" BIT NOT NULL,
 "OL_UF7" CHAR(50),
 "OL_UF7_REQUIRED" BIT NOT NULL,
 "OL_UF8" CHAR(50),
 "OL_UF8_REQUIRED" BIT NOT NULL,
 "OL_UF9" CHAR(50),
 "OL_UF9_REQUIRED" BIT NOT NULL,
 "OL_UF10" CHAR(50),
 "OL_UF10_REQUIRED" BIT NOT NULL );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
